### PR TITLE
Deployment v1.0

### PR DESCRIPTION
**Pull request by dredwerkz**
Product MVP has gone gold. Deployment 1.0 pushed to repo - pull request for 1.0 of Bookmarkd.

### CODE REVIEW

**Review by adamalrasi — APPROVED** [review]
Approve

**Review by JamesAARobertson — APPROVED** [review]
the golden moment

**Review by AmeenahJalil — APPROVED** [review]

**Review by AmeenahJalil — APPROVED** [review]
We did it !

**Review by HannahMcCabe31 — APPROVED** [review]
Final !!

**Pull request merged**
